<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="asset\menu_img\tmp.PNG" />
    <None Remove="asset\menu_img\udon_1.PNG" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="asset\menu_img\tmp.PNG" />
    <Resource Include="asset\menu_img\udon_1.PNG" />
  </ItemGroup>

</Project>
